---
title: "Sesión 3.2"
description: |
  Notebooks con R Markdown
bibliography: references.bib
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Los resultados de aprendizaje de la sesión...

-   RRP09 - **Aplicar** *notebooks* para la documentación de análisis computacionales.
-   RRP10 - **Diseñar y crear** *notebooks* para la creación de artículos científicos, informes técnicos o presentaciones.

## Los contenidos de la sesión...

-   Notebook integra de narrativa (preguntas, texto) y código (análisis, resultados)

-   Contextualización de usos de Markdown en nuestra investigación/docencia

## Actividades y materiales

**[Tiempo estimado: 2 horas]**

1.  El siguiente video "[What is R Markdown?](https://vimeo.com/178485416)" proporciona en algo más de un minuto lo que es R Markdown, es decir, un documento Markdown al cual se añade código en R (u otro lenguaje de programación) y genera un documento integrado como resultado.

2.  En esta [demo](https://drive.google.com/file/d/1vBF2jX3k9Hz8WRlZB0QC1jTB6D9cIdKw/view?usp=sharing), podéis ver un ejemplo de estructura y organización de un notebook en R Markdown.

3.  Este [vídeo](https://drive.google.com/file/d/1HXVV1lZhO2G4Ufvr4SJzHqvU-CvYwJxj/view?usp=sharing) muestra un ejemplo de un artículo reproducible [@miralles2020], que os puede servir de guía para que vuestro próximo artículo sea mucho más reproducible.

4.  Realiza un reflexión final sobre **qué aspectos quieres intentar para que tu próximo artículo sea (un poco más) reproducible*.*** ¿Si estás con tu tesis doctoral, ¿qué aspectos y practicas del curso crees que puedes adaptar de forma inmediata? Si tu perfil es más docente, ¿qué ideas (markdown, notebooks, etc) podrías aplicar a tu docencia?

## **Entrega**

-   Sube tu reflexión final (Actividad 4) en el foro **¿qué puedo hacer para que mi próximo artículo sea más reproducible** en el AV.

### 
